version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Shravani@12
      - MYSQL_DATABASE=diff_metrics
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql

  loki:
    image: grafana/loki:2.2.0
    command: -config.file=/etc/loki/loki-local.yaml
    user: "0"
    ports:
      - "3101:3100"
    environment:
      - JAEGER_AGENT_HOST=tempo
      - JAEGER_ENDPOINT=http://tempo:14268/api/traces
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    volumes:
      - ./etc/loki-local.yaml:/etc/loki/loki-local.yaml
      - ./data/loki-data:/tmp/loki

  tempo:
    image: grafana/tempo:0.7.0
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./etc/tempo-local.yaml:/etc/tempo.yaml
      - ./data/tempo-data:/tmp/tempo
    restart: unless-stopped
    ports:
      - "14268:14268"
      - "14250:14250"
      - "55680:55680"
      - "3102:3100"

  tempo-query:
    image: grafana/tempo-query:0.7.0
    command: ["--grpc-storage-plugin.configuration-file=/etc/tempo-query.yaml"]
    volumes:
      - ./etc/tempo-query.yaml:/etc/tempo-query.yaml
    ports:
      - "16686:16686"
    depends_on:
      - tempo

  primary:
    image: diffy/example-service:production

  secondary:
    image: diffy/example-service:production

  candidate:
    image: diffy/example-service:candidate

  diffy:
    image: diffy/diffy:latest
    ports:
      - "8888:8888"
      - "8880:8880"
    environment:
      spring.datasource.url: jdbc:mysql://mysql:3306/diff_metrics?useSSL=false&serverTimezone=UTC
      spring.datasource.username: root
      spring.datasource.password: Shravani@12
      spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
      spring.jpa.hibernate.ddl-auto: update
      spring.jpa.show-sql: "true"
      spring.jpa.database-platform: org.hibernate.dialect.MySQL8Dialect
      candidate: "candidate:5000"
      master.primary: "primary:5000"
      master.secondary: "secondary:5000"
      responseMode: "primary"
      service.protocol: "http"
      allowHttpSideEffects: "true"
      serviceName: "Sample Service"
      proxy.port: 8880
      http.port: 8888
      rootUrl: "localhost:8888"
      otel.javaagent.debug: "false"
      otel.metrics.exporter: "none"
      otel.traces.exporter: "jaeger"
      otel.exporter.jaeger.endpoint: "http://tempo:14250"
      otel.exporter.jaeger.traces.endpoint: "http://tempo:14250"
      otel.resource.attributes: "service.name=diffy"
      spring.application.name: "diffy"
      logging.level.web: "INFO"
      logging.level.io.opentelemetry: "WARN"
      logging.level.root: "INFO"
      logging.file.name: "/app/logs/diffy.log"
      logging.file.max-size: "10MB"
      logging.file.max-history: 1
      logging.file.clean-history-on-start: "true"
      dockerComposeLocal: "true"
    volumes:
      - ./data/logs:/app/logs
    depends_on:
      - tempo
      - mysql
      - primary
      - secondary
      - candidate

  promtail:
    image: grafana/promtail:2.2.0
    command: -config.file=/etc/promtail/promtail-local.yaml
    volumes:
      - ./etc/promtail-local.yaml:/etc/promtail/promtail-local.yaml
      - ./data/logs:/app/logs
    depends_on:
      - diffy
      - loki

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./etc/prometheus.yaml:/etc/prometheus.yaml
    entrypoint:
      - /bin/prometheus
      - --config.file=/etc/prometheus.yaml
    ports:
      - "9090:9090"
    depends_on:
      - diffy

  grafana:
    image: grafana/grafana:7.4.0-ubuntu
    volumes:
      - ./data/grafana-data/datasources:/etc/grafana/provisioning/datasources
      - ./data/grafana-data/dashboards-provisioning:/etc/grafana/provisioning/dashboards
      - ./data/grafana-data/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - tempo-query
      - loki

volumes:
  mysql_data: