
spring:
  application:
    name: diffy
  data:
    mongodb:
      host: localhost
      port: 27017
      database: diffy_metrics

server:
  port: ${http.port:8888}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: INFO
    org.springframework.data.mongodb: DEBUG
    org.mongodb.driver: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr([diffy,%X{trace_id},%X{span_id}]) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m %n%wEx"
    file:    "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr([diffy,%X{trace_id},%X{span_id}]) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m %n%wEx"

proxy:
  port: 8880

candidate: "http://localhost:9000"
master:
  primary:   "http://localhost:9100"
  secondary: "http://localhost:9200"

service:
  protocol:  "http"

serviceName: "Default Sample Service"
allowHttpSideEffects: true
responseMode:        "primary"
